###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "joy23@gmail.com",
    "password": "123"
}


### get user by id
GET http://localhost:3000/auth/3545

### get all users
GET http://localhost:3000/auth?email=joyfgfd@gmail.com


### Delete user
DELETE http://localhost:3000/auth/2444

### Update user
PATCH  http://localhost:3000/auth/344
Content-Type: application/json

{
  "email": "aa@a.com"
}
